# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

inhibit_all_warnings!

target 'JQKProtobufResponseSerializerDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for JQKProtobufResponseSerializerDemo

  pod 'AFNetworking', '~> 3.1.0'
  pod 'Protobuf', '~> 3.3.0'
  
end
